# Generated by Django 4.1.3 on 2023-01-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_admin_admins"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="lanme",
            new_name="lname",
        ),
    ]
