# Generated by Django 4.1.3 on 2023-01-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_lanme_students_lname"),
    ]

    operations = [
        migrations.CreateModel(
            name="warden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("phone", models.PositiveBigIntegerField()),
                ("mail", models.EmailField(max_length=254)),
            ],
        ),
    ]
