# Generated by Django 4.1.3 on 2023-01-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_warden_hostel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="father",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="students",
            name="mother",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
